# build
FROM openjdk:17.0-slim AS builder
WORKDIR /build

# 의존성 받기
COPY gradlew .
COPY gradle gradle
COPY settings.gradle build.gradle /build/
RUN ./gradlew -x test --no-daemon kyumall-client:build

# 소스코드 빌드
COPY kyumall-client/ /build/kyumall-client
COPY kyumall-common/ /build/kyumall-common
RUN ./gradlew -x test --no-daemon kyumall-client:build

# APP
FROM openjdk:17.0-slim
WORKDIR /app

ENV ENV_DIR=src/main/resources
COPY --from=builder /build/kyumall-client/build/libs/*.jar .
EXPOSE 8080 8181
ENTRYPOINT java -jar kyumall-client.jar

