# build
FROM openjdk:17.0-slim AS builder
WORKDIR /build

# 의존성 받기
COPY gradlew .
COPY gradle gradle
COPY settings.gradle build.gradle /build/
RUN ./gradlew -x test --no-daemon kyumall-admin:build --parallel --continue > /dev/null 2>&1 || true

# 소스 빌드
COPY kyumall-admin/ /build/kyumall-admin
COPY kyumall-common/ /build/kyumall-common
RUN ./gradlew -x test --no-daemon kyumall-admin:build

# APP
FROM openjdk:17.0-slim
WORKDIR /app

ENV ENV_DIR=src/main/resources
COPY --from=builder /build/kyumall-admin/build/libs/*.jar .
EXPOSE 8080 8181
ENTRYPOINT java -jar kyumall-admin.jar

# docker build --platform linux/amd64 -t kyumall-admin -f Dockerfile-admin .
# docker run -e SPRING_PROFILES_ACTIVE=dev kyumall-admin

