apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyumall-client
  labels:
    app: kyumall-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyumall-client
  template:
    metadata:
      labels:
        app: kyumall-client
    spec:
      containers:
        - name: kyumall-client
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: JAVA_OPTS
              value: "-XX:MaxRAMFraction=2"
#            - name: SPRING_APPLICATION_JSON
#              value: '{"logging.level.root": "debug"}'
          image: gyureal/kyumall-client:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          ports:
            - name: app
              containerPort: 8080
            - name: actuator
              containerPort: 8181

---

apiVersion: v1
kind: Service
metadata:
  name: kyumall-client
  labels:
    app: kyumall-client
spec:
  selector:
    app: kyumall-client
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 8181
      targetPort: 8181

---
# 프로메테우스 메트릭 스크랩용 오브젝트
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyumall-client-service-monitor
  labels:
    release: prometheus   # 메트릭 스크랩을 위해 설정 필수
spec:
  selector:
    matchLabels:
      app: kyumall-client
  namespaceSelector:
    any: true
  endpoints:
    - port: actuator
      path: "/actuator/prometheus"
      interval: 5s
