spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3336/kyumall
    username: root
    password: 12
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
encrypt:
  key: /MHRr8os9VnGseZ6Crf4SA==
jwt:
  secret-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2L7ArNRKU13gfByjIEmXSK1OOwdob+OCukE+6xR8TwONtPIjACnJnyEAW9VTlBwvuixqtrg2GvcsqxsO5e1LmNtDaAGkYHFOTMO89DUQWCIi9pt4RS0okKzRkckCDxt0hRLoII5V/HYJ4aMsgVGUIjz/+QeWUDwgfgO+8uq8KWsu++c0p0HIlX5mjcpVArQZLPTFkmAvW2riUKGst63HwSwiebwOzZMkkxhNZsoYKHrkEEYBGfh93SYk+ReCb88INAflksCdVZihh/DA8NAUMlS5IbiNK9oS+6bPHgSUzzf860c9YYv7gKBqirXQz/6xpGdeFaQv/B1gfcRKNQqGDAgMBAAECggEAC+dNwWT0U9lINe7H0VqyYGsISJmN4KoANCelrfRXNXky4t5DqRiFpRZGabmZ1GUDeJCKK7Llm1onPiJCg4n1PqlyN+wy8apYI5Pc7cZCHpZsKMgQVlzu+TIBeFamtHV32UaeSQ3aJLYO4kMmknQxLb/+VGSF1Yit5TENeO1RpoFv5NKwvFRAlmQboTKJGH9NCBGIbYkMWVs6UTekelDhtVV7Ac+otG1n9sySOQCKt8/rSBnhhr/RlbKFWr4U7FlYxclkzVmzUWNzATkxHKU8sIa4KtTpRSi2Ys3g7Xqye3dQRnCaeC7kCHa8qgxvWD/dkvkNDq+NS5rNE/FKwmlbQQKBgQDIE3qwrxDAyQU9vu0UWqhPixb1zFQtEyz1BczTwrChzTMKGxvf6YIqcK5uOsFhXIMLTUGnvclzM+0H/dNcOo8rOzmygoTchpEQZA/lpqmbUdltjAjqSt2WggE6tpPf0ZokaRyGTj75oGpUcejb9q037WgeSgm4hncOMJD2OhB80wKBgQDpHBjJE/qWD219LLtphUMoYUveJYJK84g9A0zIcfbGrZrIoQ7VlaBaxnlkdXcUKAKQLdWbg/ZMCbjeriCDChco/HV/wSM9ta1A2D8iLdo0xiC/kSqB7x6T3yYv7W/YFisFo9w1+xzz8yuXgtjWnUPCJ1wcA0Hps6AmnYum7LeakQKBgH1KNXqPJp6TQ4T3Gt+0JdIp96bU3aGccHq/txSkxpeMOHoLn9kIEUsiZRkCEjc2B5n8NzEj2BMcYUKv4LvQr/cSj38J3Ml8OztYbdwSEgQBrXa8SpjtaPXnU33A97khOLW0XPh951HK8ssOyhN01eQ/9wOAubWj/soT/7MxiUGhAoGAbTRacCjJ5e7ITjHcgmyJr6sVDbbouRAprNuU5vpsr1q4/nBlMK3t91ivmd5lsK2ltcGjJj3F7o1HbBqK5JifjPXoXbcvOUOZLJ2hxfNRHBQNV3E8Rq6s1n1duGo1UTfhY70F9svzHl22+D22M6RtD9G8lur3v/IEftKjj8mpoeECgYA2K9If/N3ReflzMQXEooQ8U2n4nNdgMWsPumf5K6K/rESTzmLT6XoeVH9zbZAMrM/e7F+OA/5Dfr8+g5M4ANgV0N4p66oIXt5RmdfX+/oFRciJfPfFJlPmoTftHf6+ApgBQSXxiVOzOmNShCkhDNjAZuAM+J8rdR/vxkyCHJAubA==
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAti+wKzUSlNd4HwcoyBJl0itTjsHaG/jgrpBPusUfE8DjbTyIwApyZ8hAFvVU5QcL7osara4Nhr3LKsbDuXtS5jbQ2gBpGBxTkzDvPQ1EFgiIvabeEUtKJCs0ZHJAg8bdIUS6CCOVfx2CeGjLIFRlCI8//kHllA8IH4DvvLqvClrLvvnNKdByJV+Zo3KVQK0GSz0xZJgL1tq4lChrLetx8EsInm8Ds2TJJMYTWbKGCh65BBGARn4fd0mJPkXgm/PCDQH5ZLAnVWYoYfwwPDQFDJUuSG4jSvaEvumzx4ElM83/OtHPWGL+4Cgaoq10M/+saRnXhWkL/wdYH3ESjUKhgwIDAQAB
  expire-time: 1440 # 60 * 24
logging:
  level:
    com.kyumall.kyumallclient: DEBUG
