spring:
  profiles:
    group:
      local:
        - app-local
        - ncloud
        - mail
        - actuator
        - redis-local
      dev:
        - app-dev
        - ncloud
        - mail
        - actuator
    active: local
