SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE member;
TRUNCATE TABLE verification;
TRUNCATE TABLE term;
TRUNCATE TABLE term_detail;
TRUNCATE TABLE agreement;
TRUNCATE TABLE category;
TRUNCATE TABLE product;
