SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE member;
TRUNCATE TABLE verification;
TRUNCATE TABLE term;
TRUNCATE TABLE term_detail;
TRUNCATE TABLE agreement;
TRUNCATE TABLE category;
TRUNCATE TABLE product;
TRUNCATE TABLE cart;
TRUNCATE TABLE cart_item;
TRUNCATE TABLE order_group;
TRUNCATE TABLE orders;
TRUNCATE TABLE stock;
TRUNCATE TABLE product_comment;
TRUNCATE TABLE product_comment_rating;
