apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyumall-admin
  labels:
    app: kyumall-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyumall-admin
  template:
    metadata:
      labels:
        app: kyumall-admin
    spec:
      containers:
        - name: kyumall-admin
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          #            - name: JAVA_TOOL_OPTIONS
          #              value: "-Xmx300m -Xms300m"
          #            - name: SPRING_APPLICATION_JSON
          #              value: '{"logging.level.root": "debug"}'
          image: gyureal/kyumall-admin:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          ports:
            - name: app
              containerPort: 8080
            - name: actuator
              containerPort: 8181
