apiVersion: v1
kind: Service
metadata:
  name: kyumall-admin
  labels:
    app: kyumall-admin
spec:
  selector:
    app: kyumall-admin
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 8181
      targetPort: 8181

---
# 프로메테우스 메트릭 스크랩용 오브젝트
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyumall-admin-service-monitor
  labels:
    release: prometheus   # 메트릭 스크랩을 위해 설정 필수
spec:
  selector:
    matchLabels:
      app: kyumall-admin
  namespaceSelector:
    any: true
  endpoints:
    - port: actuator
      path: "/actuator/prometheus"
      interval: 5s
